### ISSUE TITLE
An error occurred after "hicma" is installed (MacOS and Linux)

### ISSUE THREAD

**Issue by aleksada** [ecrc/exageostatR-dev#40]
ld: unknown option: --no-as-needed
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [exageostat.so] Error 1
ERROR: compilation failed for package ‘exageostat’
* removing ‘/Users/liy0h/Library/R/3.4/library/exageostat’
Installation failed: Command failed (1)
Warning message:
'head.git_repository' is deprecated.
Use 'repository_head' instead.
See help("Deprecated")

**Comment by aleksada** [comment]
I installed the package 4 times. Actually, this is the farthest I can reach for now. My system was restarted once and crushed once. The other two trials give the same error. This the message before the error.

[100%] Linking C shared library libhicma.dylib
[100%] Built target hicma
[100%] Built target hicma
Install the project...
-- Install configuration: ""
-- Installing: /Users/liy0h/Library/R/3.4/library/exageostat/lib/libhicma.dylib
-- Installing: /Users/liy0h/Library/R/3.4/library/exageostat/include/hcore_z.h
-- Installing: /Users/liy0h/Library/R/3.4/library/exageostat/include/hicma_constants.h
-- Installing: /Users/liy0h/Library/R/3.4/library/exageostat/include/hicma_struct.h
-- Installing: /Users/liy0h/Library/R/3.4/library/exageostat/include/hicma_z.h
-- Installing: /Users/liy0h/Library/R/3.4/library/exageostat/include/aux/auxcompute_z.h
-- Installing: /Users/liy0h/Library/R/3.4/library/exageostat/include/aux/auxdescutil.h
-- Installing: /Users/liy0h/Library/R/3.4/library/exageostat/lib/pkgconfig/hicma.pc
-- Installing: /Users/liy0h/Library/R/3.4/library/exageostat/share/hicma/config.log
** libs
** arch -

**Comment by aleksada** [comment]
The Ubuntu system has an error at  the same place after hicma is built. However, the error message is slightly different.

Package nlopt was not found in the pkg-config search path.
Perhaps you should add the directory containing `nlopt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nlopt' found
Package gsl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gsl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gsl' found
Package libstarpu was not found in the pkg-config search path.
Perhaps you should add the directory containing `libstarpu.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libstarpu' found
Package chameleon was not found in the pkg-config search path.
Perhaps you should add the directory containing `chameleon.pc'
to the PKG_CONFIG_PATH environment variable
No package 'chameleon' found
Package hicma was not found in the pkg-config search path.
Perhaps you should add the directory containing `hicma.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hicma' found
Package starsh was not found in the pkg-config search path.
Perhaps you should add the directory containing `starsh.pc'
to the PKG_CONFIG_PATH environment variable
No package 'starsh' found
Package nlopt was not found in the pkg-config search path.
Perhaps you should add the directory containing `nlopt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nlopt' found
Package gsl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gsl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gsl' found
Package libstarpu was not found in the pkg-config search path.
Perhaps you should add the directory containing `libstarpu.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libstarpu' found
Package chameleon was not found in the pkg-config search path.
Perhaps you should add the directory containing `chameleon.pc'
to the PKG_CONFIG_PATH environment variable
No package 'chameleon' found
Package hicma was not found in the pkg-config search path.
Perhaps you should add the directory containing `hicma.pc'
to the PKG_CONFIG_PATH environment variable
No package 'hicma' found
Package starsh was not found in the pkg-config search path.
Perhaps you should add the directory containing `starsh.pc'
to the PKG_CONFIG_PATH environment variable
No package 'starsh' found
gcc -std=gnu99 -c -fPIC -DEXAGEOSTAT_USE_HICMA -c -O3  -w -Ofast -Wall  -DVERSION=\"\" -I./include/ -I./src/include/ -I./exageostat_exact/core/include/ -I./exageostat_exact/runtime/starpu/include/ -I./misc/include/ -I ./exageostat_exact/src/include/ -I ./r-wrappers/include  -I./exageostat_approx/runtime/starpu/include/ -I./exageostat_approx/src/include/ -I./hicma/chameleon/coreblas/include/coreblas src/compute/MLE.c -o src/compute/MLE.o
In file included from ./exageostat_exact/src/include/MLE_exact.h:22:0,
                 from src/compute/../include/MLE.h:22,
                 from src/compute/MLE.c:20:
./misc/include/MLE_misc.h:31:19: fatal error: nlopt.h: No such file or directory
compilation terminated.
Makefile:48: recipe for target 'src/compute/MLE.o' failed
make: *** [src/compute/MLE.o] Error 1
ERROR: compilation failed for package ‘exageostat’
* removing ‘/home/liy0h/R/x86_64-pc-linux-gnu-library/3.6/exageostat’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/tmp/Rtmp3Qbybd/file79f769d854ff/exageostat_1.0.0.tar.gz’ had non-zero exit status

**Comment by SAbdulah** [comment]
Thanks, @aleksada. I will come back to you.

**Comment by SAbdulah** [comment]
This issue has been handled in the last merge.
