### ISSUE TITLE
lock directory "00LOCK-exageostat": error when reinstall (MacOS)

### ISSUE THREAD

**Issue by aleksada** [ecrc/exageostatR-dev#44]
When I try to reinstall exageostatR, I get the following error. I solved the problem by removing the directory. Can you prevent the issue from bash?

ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-exageostat’
Error in i.p(...) : 
  (converted from warning) installation of package ‘/var/folders/0b/s0yxp7v17f18wqsnq5xlvmb41g43vp/T//RtmpZGHBIS/file4ad37aa32de/exageostat_1.0.0.tar.gz’ had non-zero exit status

**Comment by egonzalf** [comment]
The lock is for R data integrity. And since the solution is mentioned in the error, I believe that is enough.
Handling this any other way might have undesired consequences.

**Comment by SAbdulah** [comment]
Agree with @egonzalf and this should not happen if the installation goes well (no restarting or freezing situations) from the first time.
