### ISSUE TITLE
An issue of simulate_data_exact() function

### ISSUE THREAD

**Issue by aleksada** [ecrc/exageostatR-dev#51]
The simulated y should be of length n, please replace n+1 by (n+1).

function (sigma_sq, beta, nu, dmetric = 0, n, seed = 0) 
{
    globalveclen = 3 * n
    globalvec = vector(mode = "double", length = globalveclen)
    globalvec2 = .C("gen_z_exact", as.double(sigma_sq), as.double(beta), 
        as.double(nu), as.integer(dmetric), as.integer(n), as.integer(seed), 
        as.integer(ncores), as.integer(ngpus), as.integer(dts), 
        as.integer(pgrid), as.integer(qgrid), as.integer(globalveclen), 
        globalvec = double(globalveclen))$globalvec
    newList <- list(x = globalvec2[1:n], y = globalvec2[**n + 1**:(2 * 
        n)], z = globalvec2[((2 * n) + 1):(3 * n)])
    print("back from gen_z_exact  C function call. Hit key....")
    return(newList)
}

**Comment by SAbdulah** [comment]
Fixed! @aleksada
